server:
    port: 8080
spring:
    application:
        name: ms-accounts
    datasource:
        # url: jdbc:h2:mem:testdb # Décommenter cette ligne si vous souhaitez utiliser une base de données en mémoire pour des tests.
        url: jdbc:h2:file:./data/demo;AUTO_SERVER=true
        username: admin
        password: password
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        defer-datasource-initialization: true
    h2:
        console:
            path: /h2-console
            enabled: true
#    sql:
#        init:
#            mode: always
#            schema-locations: classpath:db/schema.sql
##            data-locations: classpath:db/data.sql